// Code generated by MockGen. DO NOT EDIT.
// Source: internal/clients/gemini/client.go
//
// Generated by this command:
//
//	mockgen -source internal/clients/gemini/client.go -destination internal/clients/gemini/client_mock.go
//

// Package mock_gemini is a generated GoMock package.
package geminiclient

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockClient is a mock of Client interface.
type MockClient struct {
	ctrl     *gomock.Controller
	recorder *MockClientMockRecorder
}

// MockClientMockRecorder is the mock recorder for MockClient.
type MockClientMockRecorder struct {
	mock *MockClient
}

// NewMockClient creates a new mock instance.
func NewMockClient(ctrl *gomock.Controller) *MockClient {
	mock := &MockClient{ctrl: ctrl}
	mock.recorder = &MockClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClient) EXPECT() *MockClientMockRecorder {
	return m.recorder
}

// GenerateMessage mocks base method.
func (m *MockClient) GenerateMessage(ctx context.Context, query string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateMessage", ctx, query)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GenerateMessage indicates an expected call of GenerateMessage.
func (mr *MockClientMockRecorder) GenerateMessage(ctx, query any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateMessage", reflect.TypeOf((*MockClient)(nil).GenerateMessage), ctx, query)
}
